import type { Metadata } from 'next';
import { inter } from './_ui/fonts';
import './_ui/token.css';
import './_ui/globals.css';
import { HeaderWrapper } from './_components/Header/HeaderWrapper';
import { Footer } from './_components/Footer/Footer';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HeaderWrapper />
        {children}
        <Footer />
      </body>
    </html>
  )
}
